/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simplecalc;

/**
 *
 * @author Azande
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    double num1 = 0;
    double num2 = 0;
    String operator = "";
    boolean startNewNumber = true;

    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answer_btn = new javax.swing.JButton();
        numOne = new javax.swing.JButton();
        numFour = new javax.swing.JButton();
        numSeven = new javax.swing.JButton();
        numZero = new javax.swing.JButton();
        numTwo = new javax.swing.JButton();
        numFive = new javax.swing.JButton();
        numEight = new javax.swing.JButton();
        numZeroZero = new javax.swing.JButton();
        numThree = new javax.swing.JButton();
        numSix = new javax.swing.JButton();
        numNine = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        subtract_btn = new javax.swing.JButton();
        multiply_btn = new javax.swing.JButton();
        comma = new javax.swing.JButton();
        screen = new javax.swing.JTextField();
        divide_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        answer_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        answer_btn.setText("Ans");
        answer_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        answer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_btnActionPerformed(evt);
            }
        });

        numOne.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numOne.setText("1");
        numOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOneActionPerformed(evt);
            }
        });

        numFour.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numFour.setText("4");
        numFour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFourActionPerformed(evt);
            }
        });

        numSeven.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numSeven.setText("7");
        numSeven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSevenActionPerformed(evt);
            }
        });

        numZero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numZero.setText("0");
        numZero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numZeroActionPerformed(evt);
            }
        });

        numTwo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numTwo.setText("2");
        numTwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTwoActionPerformed(evt);
            }
        });

        numFive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numFive.setText("5");
        numFive.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numFiveActionPerformed(evt);
            }
        });

        numEight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numEight.setText("8");
        numEight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numEightActionPerformed(evt);
            }
        });

        numZeroZero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numZeroZero.setText("00");
        numZeroZero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numZeroZeroActionPerformed(evt);
            }
        });

        numThree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numThree.setText("3");
        numThree.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numThreeActionPerformed(evt);
            }
        });

        numSix.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numSix.setText("6");
        numSix.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numSixActionPerformed(evt);
            }
        });

        numNine.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        numNine.setText("9");
        numNine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numNineActionPerformed(evt);
            }
        });

        clear_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clear_btn.setText("AC");
        clear_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        delete_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        delete_btn.setText("Del");
        delete_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_btn.setText("+");
        add_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        subtract_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtract_btn.setText("-");
        subtract_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subtract_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtract_btnActionPerformed(evt);
            }
        });

        multiply_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        multiply_btn.setText("x");
        multiply_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multiply_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiply_btnActionPerformed(evt);
            }
        });

        comma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comma.setText(",");
        comma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaActionPerformed(evt);
            }
        });

        screen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        screen.setText("0");
        screen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        screen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screenActionPerformed(evt);
            }
        });

        divide_btn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        divide_btn.setText("/");
        divide_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        divide_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divide_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subtract_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(multiply_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(divide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(screen)
                    .addComponent(answer_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(screen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOne, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numThree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtract_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numFour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numFive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numSix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numEight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numNine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numZero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numZeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiply_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divide_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(answer_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appendNumber(String number) {
        if (startNewNumber || screen.getText().equals("0")) {
            screen.setText(number);
            startNewNumber = false;
        } else {
            screen.setText(screen.getText() + number);
        }
    }
    


    private void numOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOneActionPerformed
        // TODO add your handling code here:
        appendNumber("1");
    }//GEN-LAST:event_numOneActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
        screen.setText("0");
        num1 = 0;
        num2 = 0;
        operator = "";
        startNewNumber = true;
    }//GEN-LAST:event_clear_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        String text = screen.getText();
        if (text.length() > 1) {
            screen.setText(text.substring(0, text.length() - 1));
        } else {
            screen.setText("0");
            startNewNumber = true;
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(screen.getText());
        operator = "+";
        startNewNumber = true;
    }//GEN-LAST:event_add_btnActionPerformed

    private void subtract_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtract_btnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(screen.getText());
        operator = "-";
        startNewNumber = true;
    }//GEN-LAST:event_subtract_btnActionPerformed

    private void multiply_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiply_btnActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(screen.getText());
        operator = "*";
        startNewNumber = true;
    }//GEN-LAST:event_multiply_btnActionPerformed

    private void commaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commaActionPerformed

    private void numTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTwoActionPerformed
        // TODO add your handling code here:
        appendNumber("2");
    }//GEN-LAST:event_numTwoActionPerformed

    private void screenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screenActionPerformed

    private void numThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numThreeActionPerformed
        // TODO add your handling code here:
        appendNumber("3");
    }//GEN-LAST:event_numThreeActionPerformed

    private void numFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFourActionPerformed
        // TODO add your handling code here:
        appendNumber("4");
    }//GEN-LAST:event_numFourActionPerformed

    private void numFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numFiveActionPerformed
        // TODO add your handling code here:
        appendNumber("5");
    }//GEN-LAST:event_numFiveActionPerformed

    private void numSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSixActionPerformed
        // TODO add your handling code here:
        appendNumber("6");
    }//GEN-LAST:event_numSixActionPerformed

    private void numSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numSevenActionPerformed
        // TODO add your handling code here:
        appendNumber("7");
    }//GEN-LAST:event_numSevenActionPerformed

    private void numEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numEightActionPerformed
        // TODO add your handling code here:
        appendNumber("8");
    }//GEN-LAST:event_numEightActionPerformed

    private void numNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numNineActionPerformed
        // TODO add your handling code here:
        appendNumber("9");
    }//GEN-LAST:event_numNineActionPerformed

    private void numZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numZeroActionPerformed
        // TODO add your handling code here:
        appendNumber("0");
    }//GEN-LAST:event_numZeroActionPerformed

    private void numZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numZeroZeroActionPerformed
        // TODO add your handling code here:
        appendNumber("00");
    }//GEN-LAST:event_numZeroZeroActionPerformed

    private void divide_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divide_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divide_btnActionPerformed

    private void answer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_btnActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(screen.getText());
        double result = 0;

        switch (operator) {
            case "+" -> result = num1 + num2;
            case "-" -> result = num1 - num2;
            case "*" -> result = num1 * num2;
            case "/" -> {
                if (num2 == 0) {
                    screen.setText("Error");
                    return;
                }
                result = num1 / num2;
            }
        }

        screen.setText(String.valueOf(result));
        startNewNumber = true;
    }//GEN-LAST:event_answer_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton answer_btn;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton comma;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton divide_btn;
    private javax.swing.JButton multiply_btn;
    private javax.swing.JButton numEight;
    private javax.swing.JButton numFive;
    private javax.swing.JButton numFour;
    private javax.swing.JButton numNine;
    private javax.swing.JButton numOne;
    private javax.swing.JButton numSeven;
    private javax.swing.JButton numSix;
    private javax.swing.JButton numThree;
    private javax.swing.JButton numTwo;
    private javax.swing.JButton numZero;
    private javax.swing.JButton numZeroZero;
    private javax.swing.JTextField screen;
    private javax.swing.JButton subtract_btn;
    // End of variables declaration//GEN-END:variables
}
